# Generated by Django 4.1.4 on 2023-04-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="icon_default",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="icon_filename",
            field=models.CharField(default="default.gif", max_length=32),
        ),
        migrations.AddField(
            model_name="user",
            name="icon_version",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="readme",
            field=models.TextField(blank=True, default="# Hello, world!", null=True),
        ),
    ]
