# Generated by Django 4.1.9 on 2023-07-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_bio_user_icon_default_user_icon_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_deletion_token',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='account_deletion_token_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_change_token',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_change_token_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='force_logout_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('cherry', 'Cherry')], default='default', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='Hello, world!', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='readme',
            field=models.TextField(blank=True, default='# Hello, world!'),
        ),
    ]
