# Generated by Django 4.1.9 on 2023-07-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_account_deletion_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('default', 'MetroTech Hub'), ('classic', 'Classical Charms'), ('midnight_abyss', 'Midnight Abyss'), ('cherry', 'Cherry Crush')], default='default', max_length=32),
        ),
    ]
